"""add actual recommend feature to evaluation

Revision ID: 19b8bafda6df
Revises: 30e614a8d334
Create Date: 2023-01-20 14:52:02.454062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b8bafda6df'
down_revision = '30e614a8d334'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userevaluations', sa.Column('actual_recommendation_feature', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userevaluations', 'actual_recommendation_feature')
    # ### end Alembic commands ###
