"""add feature to click model

Revision ID: 30e614a8d334
Revises: a44059c05eaa
Create Date: 2023-01-20 14:44:29.834859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e614a8d334'
down_revision = 'a44059c05eaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userclicks', sa.Column('recommendation_feature', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userclicks', 'recommendation_feature')
    # ### end Alembic commands ###
