"""extend painting model

Revision ID: 859318f19de9
Revises: ba9d683d7b26
Create Date: 2023-01-18 21:57:09.011202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859318f19de9'
down_revision = 'ba9d683d7b26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paintings', sa.Column('title', sa.String(length=1024), nullable=True))
    op.add_column('paintings', sa.Column('maker', sa.String(length=256), nullable=True))
    op.add_column('paintings', sa.Column('description', sa.String(length=4096), nullable=True))
    op.add_column('paintings', sa.Column('year', sa.String(length=256), nullable=True))
    op.add_column('paintings', sa.Column('url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paintings', 'url')
    op.drop_column('paintings', 'year')
    op.drop_column('paintings', 'description')
    op.drop_column('paintings', 'maker')
    op.drop_column('paintings', 'title')
    # ### end Alembic commands ###
