"""rename field

Revision ID: 9604f333caca
Revises: f4dc2d9fb6f2
Create Date: 2023-01-26 13:44:27.958095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9604f333caca'
down_revision = 'f4dc2d9fb6f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userevaluationresults', sa.Column('user_evaluation_id', sa.Integer(), nullable=True))
    op.drop_constraint('userevaluationresults_user_id_fkey', 'userevaluationresults', type_='foreignkey')
    op.create_foreign_key(None, 'userevaluationresults', 'userevaluations', ['user_evaluation_id'], ['id'])
    op.drop_column('userevaluationresults', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userevaluationresults', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'userevaluationresults', type_='foreignkey')
    op.create_foreign_key('userevaluationresults_user_id_fkey', 'userevaluationresults', 'userevaluations', ['user_id'], ['id'])
    op.drop_column('userevaluationresults', 'user_evaluation_id')
    # ### end Alembic commands ###
