"""create user click model

Revision ID: ba9d683d7b26
Revises: b5dd3195f199
Create Date: 2023-01-18 17:22:03.427691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9d683d7b26'
down_revision = 'b5dd3195f199'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userclicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('painting_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('painting_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['painting_id'], ['paintings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('paintings', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paintings', sa.Column('path', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_table('userclicks')
    # ### end Alembic commands ###
