"""Add features to painting

Revision ID: f482af7d03b2
Revises: 859318f19de9
Create Date: 2023-01-19 15:41:33.818181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f482af7d03b2'
down_revision = '859318f19de9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paintings', sa.Column('color', sa.String(length=16), nullable=True))
    op.add_column('paintings', sa.Column('art_style', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paintings', 'art_style')
    op.drop_column('paintings', 'color')
    # ### end Alembic commands ###
