import enum


class ArtStyles(enum.Enum):
    ABSTRACT_EXPRESSIONISM = 0
    ACTION_PAINTING = 1
    ANALYTICAL_CUBISM = 2
    ART_NOUVEAU = 3
    BAROQUE = 4
    COLOR_FIELD_PAINTING = 5
    CONTEMPORARY_REALISM = 6
    CUBISM = 7
    EARLY_RENAISSANCE = 8
    EXPRESSIONISM = 9
    FAUVISM = 10
    HIGH_RENAISSANCE = 11
    IMPRESSIONISM = 12
    MANNERISM_LATE_RENAISSANCE = 13
    MINIMALISM = 14
    NAIVE_ART_PRIMITIVISM = 15
    NEW_REALISM = 16
    NORTHERN_RENAISSANCE = 17
    POINTILLISM = 18
    POP_ART = 19
    POST_IMPRESSIONISM = 20
    REALISM = 21
    ROCOCO = 22
    ROMANTICISM = 23
    SYMBOLISM = 24
    SYNTHETIC_CUBISM = 25
    UKIYO_E = 26


class FeatureTypes(enum.Enum):
    ART_STYLE = 0
    COLOR = 1
    DESCRIPTION = 2
    VISUAL = 3
    ALL = 4
